# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lottie_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lottie_iOS

  pod 'lottie-ios'


  target 'Lottie_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lottie_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
